### ISSUE TITLE
HALAMAN LOKET ( ADMIN ) 

### ISSUE THREAD

**Issue by ternakkode** [Fakhri1999/antrian-laravel#10]
tolong buatkan halaman loket ri gambarane koyo ngene : 

di paling atas tambahin 1 button
text : RESET SEMUA 
efeke semua data di table loket status, id_petugas, nomor antrian jadi 0

nde bawah e ada 9 kotak foreach teko tabel loket 
seng ditampilno nde kotak iku :
nomor loket
status : 0 ditampilno nonaktif sementara nek 1 ditampilno : 
- nama petugas ( inner join id_petugas teko tabel loket mbe id nde tabel petugas)
- nomor antrian
- jenis layanan yang dipakai 
gae oleh jenis layanane : 
nomor antriane kan wes ono engko inner join tabel antrian mbe tabel layanan pilihan_layanan antrian = id layanan

**Comment by Fakhri1999** [comment]
fixed
