### ISSUE TITLE
HALAMAN LOKET (PETUGAS)

### ISSUE THREAD

**Issue by ternakkode** [Fakhri1999/antrian-laravel#11]
tolong buatkan halaman loket gae petugas ri gambarane koyo ngene (mirip loket admin) :

ada 9 kotak foreach teko tabel loket
seng ditampilno nde kotak iku :
nomor loket
status : 0 ditampilno nonaktif dan kei button masuk engko redirect ke halaman baru link e petugas/loket/id_loket isine kosongan sek ae 
aksi nde db : 
UPDATE tabel loket bagian status jd 1
UPDATE tabel petugas status dadi sesuai nomer loket

sementara nek 1 ditampilno :

nama petugas ( inner join id_petugas teko tabel loket mbe id nde tabel petugas)
nomor antrian
jenis layanan yang dipakai
gae oleh jenis layanane :
nomor antriane kan wes ono engko inner join tabel antrian mbe tabel layanan pilihan_layanan antrian = id layanan

**Comment by Fakhri1999** [comment]
fixed
