### ISSUE TITLE
REVISI HALAMAN LOKET (ADMIN)

### ISSUE THREAD

**Issue by ternakkode** [Fakhri1999/antrian-laravel#13]
ri nde sebelum button reset tolong tambahin button gae tambah loket terus gae modal inputane nama loket tok ae

terus bagian kotak2 e tambahi

Loket aktif : nde bagian paling bawah tambahi button hapus dengan width 50% dan button keluarkan dengan width 50%

Loket nonaktif : bagian paling bawah kei button hapus width 100%

**Comment by ternakkode** [comment]
TAMBAHAN : aku coba ngakses halaman loket datane ga metu ri sementara halaman lain datane metu

**Comment by Fakhri1999** [comment]
fixed
