### ISSUE TITLE
HALAMAN DETAIL LOKET PETUGAS

### ISSUE THREAD

**Issue by ternakkode** [Fakhri1999/antrian-laravel#14]
halamane saiki : http://localhost:8000/lokets
tolong dirubah ke http://localhost:8000/petugas/loket/id_loket

HALO M. FIRHAN AZMI NOR GANTI HALO NAMA PETUGAS

pilihan select iku sesuai dengan list layanan

ada 4 button sementara kei fungsi gae 3 button : 

button keluar ngerubah : 
tabel loket ( id sama kaya yang yang dimasukkin) : 
status jd 0 id_petugas jd 0 id_antrian jd 0
tabel petugas status jd 0

button skip : 
ngerubah status nde tabel antrian dadi 9
terus data antrian seng ditampilkan data terdekat sesuai dengan select layanan seng dipilih

button next: 
ngerubah status nde tabel antrian dadi 10
terus data antrian seng ditampilkan data terdekat sesuai dengan select layanan seng dipilih

*keterangan tambahan : 
layanan id 1 : no antrian A001, A002
layanan id 2 : no antrian B001, B002

**Comment by ternakkode** [comment]
tambahan pas nge klik button skip dan next

id_petugas nde tabel antrian isi sesuai id petugase

**Comment by ternakkode** [comment]
nde pilihan select iku tulis
nama layanan ( antrian : jumlah yang mengantri dalam angka ) -> ngerti jumlah yang mengantri teko tabel antrian seng pilihan_layanane sesuai id layanan iku & statuse masih 1

**Comment by Fakhri1999** [comment]
fixed
