### ISSUE TITLE
HALAMAN KEPUASAN PELANGGAN

### ISSUE THREAD

**Issue by ternakkode** [Fakhri1999/antrian-laravel#15]
gaekno halaman kepuasan pelanggan link e iku sesuai dengan id_loket e seperti ini : 
http://localhost:8000/petugas/loket/id_loket/kepuasan

isi 2 emot dari : 
https://drive.google.com/drive/folders/1qCwM3ZXlCslQFl6_9v3_Kiz1tyKrB4Bs?usp=sharing
kiri foto senyum dibawahe teks puas, kanan foto sedih dibawahe teks tidak puas warna teks e atur orange ae

kolom seng ono foto senyum & teks puas diklik efeke : 
ngerubah kepuasan nde tabel antrian dadi "PUAS"

kolom seng ono foto SEDIH & teks TIDAK PUAS diklik efeke : 
ngerubah kepuasan nde tabel antrian dadi "TIDAK PUAS"

id antriane diambil teko id antrian seng lagi di proses nde loket tersebut

contoh : loket proses antrian B300 dadi iku kepuasan gae antrian B300 lalu pas loket lanjut ke antrian B301 kepuasane yo ganti gae antrian B301

**Comment by Fakhri1999** [comment]
need more time to fix a bug that I just found. I will fix it tonight. 
Actually the system is running very well, but I still need to fix bug when I'm trying to get the current queue in a counter. Don't forget to read the readme to activate the broadcast for real-time queue and kepuasan page

**Comment by Fakhri1999** [comment]
fixed
