### ISSUE TITLE
HALAMAN DISPLAY

### ISSUE THREAD

**Issue by ternakkode** [Fakhri1999/antrian-laravel#16]
![image](https://user-images.githubusercontent.com/40066340/74135115-4e067f80-4c1e-11ea-9186-e43f09bc04f6.png)

1. Tiap ada antrian yang masuk ke loket dipanggil lewat yang kotak dikiri ( 1 antrian terbaru yang masuk )
2. Jika ada 2 antrian atau lebih masuk bersamaan dipanggil satu persatu dari yang paling dahulu.
3. 9 kotak dikanan sesuaikan dengan loket yang aktif jika loket yang aktif hanya 4, hanya tampilkan 4 tiket
4. Suara panggilan 
in.wav
lanjut ke responsive voice "ANTRIAN NOMOR DXXX HARAP KE LOKET B300

**Comment by Fakhri1999** [comment]
fixed
