### ISSUE TITLE
REVISI DETAIL LOKET(PETUGAS)

### ISSUE THREAD

**Issue by ternakkode** [Fakhri1999/antrian-laravel#17]
![image](https://user-images.githubusercontent.com/40066340/74113534-60a99600-4bd7-11ea-9be8-555fd0e26d33.png)

ri tolong dirubah gae menu selecte tetep nampilno kabeh layanan meski antriane kosong, nek antriane kosong tulis ae nama layanan ( Antrian Kosong )

**Comment by Fakhri1999** [comment]
fixed
