### ISSUE TITLE
BACK END HALAMAN UNTUK PENGUNJUNG

### ISSUE THREAD

**Issue by ternakkode** [Fakhri1999/antrian-laravel#2]
gae halaman isine 6 button terus nek tiap button dipencet bakal insert data nde tabel antrian

- nomor antrian, nek button pertama diklik insert e (A001, A002) button kedua di klik insert e (B001,B002,B003)

terus angka nomor antrian iku tiap hari mulai dari 0
contoh saiki tgl 1 dadi angka antriane sampe 350
besok tanggal 2 ketika button e di klik angka antrian balik teko 0

- waktu pembuatan isi tanggal bulan tahun jam menit detik

- status isi 1

**Comment by Fakhri1999** [comment]
fixed
