### ISSUE TITLE
Halaman Riwayat Antrian User

### ISSUE THREAD

**Issue by ternakkode** [Fakhri1999/antrian-laravel#29]
Halaman Riwayat Antrian Untuk User Dalam bentuk table gae table bootstrap 4++

Data Yang ditampilkan :
1. Angka Urut
2. Nomor Antrian
3. Layanan
4. Waktu (tanggal bulan tahun ae )
5. Status
6. Hasil ( iki kei link ke halaman kosong sek ae ri & parameter e gae nomor antrian dadi contoh link e antrian/nomor antrian )

**Comment by Fakhri1999** [comment]
fixed
