### ISSUE TITLE
LOGIN & HALAMAN ADMIN

### ISSUE THREAD

**Issue by ternakkode** [Fakhri1999/antrian-laravel#3]
1.  Aku sudah upload file resource dari template ke folder public aku kasih nama foldernya template
2. Tolong buat halaman /admin jika ada session load view admin/index jika tidak ada redirect ke login 
3. Login diberi notif pake sweetalert jika password salah
4. Setelah login diarahkan langsung ke halaman index tanpa ada notif pake sweetalert

tolong link css & js ke folder templatenya jg

**Comment by Fakhri1999** [comment]
fixed
