### ISSUE TITLE
Revisi Halaman Dashboard User & Admin Layanan

### ISSUE THREAD

**Issue by ternakkode** [Fakhri1999/antrian-laravel#30]
Tambahi ndek CRUD Layanan inputan anyar estimasi waktu dalam bentuk menit.

Tiap Button Layanan tambahi keterangan :

Nomor Antrian yang sedang dilayani : 
Jumlah Antrian : 
Estimasi Waktu : ( jumlah * estimasi per antrian )

**Comment by Fakhri1999** [comment]
fixed
