### ISSUE TITLE
CRUD PETUGAS

### ISSUE THREAD

**Issue by ternakkode** [Fakhri1999/antrian-laravel#4]
1. Aku wes gae halaman data petugas tolong gae CRUDne
* tambah & update e load gae modal ae 
*proses e tetep no reload ya 
* notifikasi error/sukses gae sweetalert

2. Gae read e kan ono kolom Status iku get nomor_loket teko tabel loket inner join nde id petugas

**Comment by Fakhri1999** [comment]
fixed
