### ISSUE TITLE
CRUD LAYANAN

### ISSUE THREAD

**Issue by ternakkode** [Fakhri1999/antrian-laravel#8]
routes wes tak tambahno /admin/layanan

keterangan untuk view data : 

* nde db status 0, berarti ditampilno nonaktif
* nde db status 1, berarti ditampilno aktif
* kolom aksi tambah 1 button, nek nde db status 0 button e aktifkan, nek nde db status 1 button e nonaktifkan nahh aksine ngerubah nilai status dari 0 ke 1 dan sebaliknya

**Comment by ternakkode** [comment]
button aktifkan warna ijo button nonaktif warna merah

**Comment by Fakhri1999** [comment]
fix
